# Configuración para Railway con Nixpacks
[phases.build]
cmds = [
    "mvn clean package -DskipTests",
    "find target -name '*.jar' -not -name '*-sources.jar' -not -name '*-javadoc.jar' | head -1 | xargs -I {} cp {} app.jar"
]

[phases.start]
cmd = "java -jar app.jar"

[variables]
JAVA_OPTS = "-Xmx512m"
